config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  resources :users
  resources :tools
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tools

  validates :name, presence: true

  def self.search(query)
    where("name LIKE ?", "%#{query}%")
  end
end

app/models/tool.rb
class Tool < ApplicationRecord
  has_many :user_tool_associations, dependent: :destroy
  has_many :users, through: :user_tool_associations
  belongs_to :category, optional: true

  validates :name, presence: true

  def self.search(query)
    where("name LIKE ?", "%#{query}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_tool_associations, dependent: :destroy
  has_many :tools, through: :user_tool_associations

  validates :full_name, presence: true

  def self.search(query)
    where("full_name LIKE ?", "%#{query}%")
  end
end

app/models/user_tool_association.rb
class UserToolAssociation < ApplicationRecord
  belongs_to :user
  belongs_to :tool
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.includes(:tools).all
    @categories = @categories.search(params[:search]) if params[:search].present?
  end

  def edit
    @category = Category.includes(:tools).find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to categories_path, notice: "Category was successfully updated."
    else
      render :edit
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path, notice: "Category was successfully created."
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.tools.update_all(category_id: nil)
    @category.destroy

    redirect_to categories_path, notice: "Category was successfully deleted."
  end

  private

  def category_params
    params.require(:category).permit(:name, tool_ids: [])
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
    @tools = Tool.includes(:users, :category).all
    @tools = @tools.search(params[:search]) if params[:search].present?
  end

  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_params)

    if @tool.save
      redirect_to tools_path, notice: "Tool was successfully created."
    else
      render :new
    end
  end

  def edit
    @tool = Tool.includes(:users, :category).find(params[:id])
  end

  def update
    @tool = Tool.find(params[:id])

    if @tool.update(tool_params)
      redirect_to tools_path, notice: "Tool was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @tool = Tool.find(params[:id])
    @tool.destroy

    redirect_to tools_path, notice: "Tool was successfully deleted."
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :category_id, user_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(:tools).all
    @users = @users.search(params[:search]) if params[:search].present?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, notice: "User was successfully created."
    else
      render :new
    end
  end

  def edit
    @user = User.includes(:tools).find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to users_path, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path, notice: "User was successfully deleted."
  end

  private

  def user_params
    params.require(:user).permit(:full_name, tool_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<h1>Category: <%= category.name %></h1>
<div>
  <strong>Associated Tools:</strong>
  <% category.tools.each do |tool| %>
    <%= link_to tool, style: "text-decoration:none" do %>
      <span><%= tool.name %></span>
    <% end %>
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: @category, url: categories_path) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :tools %>
    <% Tool.all.each do |tool| %>
      <label>
        <%= check_box_tag "category[tool_ids][]", tool.id %>
        <%= tool.name %>
      </label><br>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= form_with(model: @category, url: category_path(@category), method: :patch) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <br />

  <div>
    <%= form.label :tools %>
    <% Tool.all.each do |tool| %>
      <label>
        <%= check_box_tag "category[tool_ids][]", tool.id, @category.tools.include?(tool) %>
        <%= tool.name %>
      </label>
    <% end %>
  </div>
  <br />

  <div>
    <%= form.submit "Update Category" %>
    <%= link_to "Cancel", categories_path %>
  </div>
<% end %>

app/views/categories/index.html.erb
<h1>List of Categories</h1>
<p style="color: green"><%= notice %></p>

<%= link_to "View all Tools", tools_path %>
<%= link_to "Add New Category", new_category_path %>
<br />
<br />

<%= form_with(url: categories_path, method: "get") do |form| %>
  <div>
    <%= form.label :search, "Search Categories:" %>
    <%= form.text_field :search %>
    <%= form.submit "Search" %>
    <%= link_to "Clear Search", categories_path %>
  </div>
<% end %>
<br />

<table>
  <thead>
    <tr>
      <th>Category Name</th>
      <th>Associated Tools</th>
      <th>Edit</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td style="border: 1px solid #333"> <%= category.name %> </td>
        <td style="border: 1px solid #333">
          <% category.tools.each do |tool| %>
            <%= tool.name %>, 
          <% end %>
        </td>
        <td style="border: 1px solid #333">
          <%= link_to "Edit", edit_category_path(category) %>
        </td>
        <td style="border: 1px solid #333">
          <%= button_to "Delete this category", category, method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1>Add New Category</h1>

<%= link_to "Back to categories", categories_path %>

<%= render "form", category: @category %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSoftwareTrackingTool</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tools/_form.html.erb
<%= form_with(model: @tool, url: tools_path) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name, prompt: "Select a category" %>
  </div>

  <div>
    <%= form.label :users %>
    <% User.all.each do |user| %>
      <label>
        <%= check_box_tag "tool[user_ids][]", user.id %>
        <%= user.full_name %>
      </label><br>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tools/_tool.html.erb
<h1>Tool: <%= tool.name %></h1>
<div>
  <div>
    <strong>Users:</strong>
    <% tool.users.each do |user| %>
      <%= link_to user, style: "text-decoration:none" do %>
        <span><%= user.full_name %></span>
      <% end %>
    <% end %>
  </div>

  <div>
    <strong>Category:</strong>
    <%= link_to tool.category, style: "text-decoration:none" do %>
      <span><%= tool.category.name %></span>
    <% end %>
  </div>
</div>

app/views/tools/edit.html.erb
<h1>Edit Tool</h1>

<%= form_with(model: @tool, url: tool_path(@tool), method: :patch) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <br />

  <div>
    <%= form.label :category %>
    <%= form.collection_select(:category_id, Category.all, :id, :name, prompt: "Select a category") %>
  </div>
  <br />

  <div>
    <%= form.label :users %>
    <% User.all.each do |user| %>
      <label>
        <%= check_box_tag "tool[user_ids][]", user.id, @tool.users.include?(user) %>
        <%= user.full_name %>
      </label>
    <% end %>
  </div>
  <br />

  <div>
    <%= form.submit "Update Tool" %>
    <%= link_to "Cancel", tools_path %>
  </div>
<% end %>

app/views/tools/index.html.erb
<h1>List of Tools</h1>
<p style="color: green"><%= notice %></p>

<%= link_to "View all Users", users_path %>
<%= link_to "View all Categories", categories_path %>
<%= link_to "Add New Tool", new_tool_path %>
<br />
<br />

<%= form_with(url: tools_path, method: "get") do |form| %>
  <div>
    <%= form.label :search, "Search Tools:" %>
    <%= form.text_field :search %>
    <%= form.submit "Search" %>
    <%= link_to "Clear Search", tools_path %>
  </div>
<% end %>
<br />

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Users</th>
      <th>Category</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @tools.each do |tool| %>
      <tr>
        <td style="border: 1px solid #333"> <%= tool.name %> </td>
        <td style="border: 1px solid #333">
          <% tool.users.each do |user| %>
            <%= user.full_name %>, 
          <% end %>
        </td>
        <td style="border: 1px solid #333">
          <%= tool.category&.name %> 
        </td>
        <td style="border: 1px solid #333">
          <%= link_to "Edit", edit_tool_path(tool) %>
        </td>
        <td style="border: 1px solid #333">
          <%= button_to "Delete this tool", tool, method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tools/new.html.erb
<h1>Add New Tool</h1>

<%= link_to "Back to tools", tools_path %>

<%= render "form", tool: @tool %>

app/views/users/_form.html.erb
<%= form_with(model: @user, url: users_path) do |form| %>
  <div>
    <%= form.label :full_name %>
    <%= form.text_field :full_name %>
  </div>

  <div>
    <%= form.label :tools %>
    <% Tool.all.each do |tool| %>
      <label>
        <%= check_box_tag "user[tool_ids][]", tool.id %>
        <%= tool.name %>
      </label><br>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<h1>User: <%= user.full_name %></h1>

<div>
  <strong>Tools:</strong>
  <% user.tools.each do |tool| %>
    <%= link_to tool, style: "text-decoration:none" do %>
      <span><%= tool.name %></span>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_with(model: @user, url: user_path(@user), method: :patch) do |form| %>
  <div>
    <%= form.label :full_name %>
    <%= form.text_field :full_name %>
  </div>
  <br />

  <div>
    <%= form.label :tools %>
    <% Tool.all.each do |tool| %>
      <label>
        <%= check_box_tag "user[tool_ids][]", tool.id, @user.tools.include?(tool) %>
        <%= tool.name %>
      </label>
    <% end %>
  </div>
  <br />

  <div>
    <%= form.submit "Update User" %>
    <%= link_to "Cancel", users_path %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>List of Users</h1>
<p style="color: green"><%= notice %></p>

<%= link_to "View all Tools", tools_path %>
<%= link_to "Add New User", new_user_path %>
<br />
<br />

<%= form_with(url: users_path, method: "get") do |form| %>
  <div>
    <%= form.label :search, "Search Users:" %>
    <%= form.text_field :search %>
    <%= form.submit "Search" %>
    <%= link_to "Clear Search", users_path %>
  </div>
<% end %>
<br />

<table>
  <thead>
    <tr>
      <th>Full Name</th>
      <th>Software tools</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td style="border: 1px solid #333"> <%= user.full_name %> </td>
        <td style="border: 1px solid #333">
          <% user.tools.each do |tool| %>
            <%= tool.name %>,
          <% end %>
        </td>
        <td style="border: 1px solid #333">
          <%= link_to "Edit", edit_user_path(user) %>
        </td>
        <td style="border: 1px solid #333">
          <%= button_to "Delete this user", user, method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Add New User</h1>

<%= link_to "Back to users", users_path %>

<%= render "form", user: @user %>